// Generated by gencpp from file model_ops/objectOp.msg
// DO NOT EDIT!


#ifndef MODEL_OPS_MESSAGE_OBJECTOP_H
#define MODEL_OPS_MESSAGE_OBJECTOP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace model_ops
{
template <class ContainerAllocator>
struct objectOp_
{
  typedef objectOp_<ContainerAllocator> Type;

  objectOp_()
    : ox(0)
    , oy(0)
    , newOp(false)  {
    }
  objectOp_(const ContainerAllocator& _alloc)
    : ox(0)
    , oy(0)
    , newOp(false)  {
    }



   typedef int16_t _ox_type;
  _ox_type ox;

   typedef int16_t _oy_type;
  _oy_type oy;

   typedef uint8_t _newOp_type;
  _newOp_type newOp;




  typedef boost::shared_ptr< ::model_ops::objectOp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::model_ops::objectOp_<ContainerAllocator> const> ConstPtr;

}; // struct objectOp_

typedef ::model_ops::objectOp_<std::allocator<void> > objectOp;

typedef boost::shared_ptr< ::model_ops::objectOp > objectOpPtr;
typedef boost::shared_ptr< ::model_ops::objectOp const> objectOpConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::model_ops::objectOp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::model_ops::objectOp_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace model_ops

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'model_ops': ['/home/cc/ee106a/fa15/class/ee106a-as/ros_ws/final_proj/src/model_ops/msg', '/home/cc/ee106a/fa15/class/ee106a-as/ros_ws/final_proj/src/model_ops/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::model_ops::objectOp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::model_ops::objectOp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::model_ops::objectOp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::model_ops::objectOp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::model_ops::objectOp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::model_ops::objectOp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::model_ops::objectOp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "43114985d67bb1bd58bb205d1a0a2adc";
  }

  static const char* value(const ::model_ops::objectOp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x43114985d67bb1bdULL;
  static const uint64_t static_value2 = 0x58bb205d1a0a2adcULL;
};

template<class ContainerAllocator>
struct DataType< ::model_ops::objectOp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "model_ops/objectOp";
  }

  static const char* value(const ::model_ops::objectOp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::model_ops::objectOp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 ox\n\
int16 oy\n\
bool newOp\n\
";
  }

  static const char* value(const ::model_ops::objectOp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::model_ops::objectOp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ox);
      stream.next(m.oy);
      stream.next(m.newOp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct objectOp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::model_ops::objectOp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::model_ops::objectOp_<ContainerAllocator>& v)
  {
    s << indent << "ox: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ox);
    s << indent << "oy: ";
    Printer<int16_t>::stream(s, indent + "  ", v.oy);
    s << indent << "newOp: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.newOp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MODEL_OPS_MESSAGE_OBJECTOP_H
