// Generated by gencpp from file image_to_grid/gridZumy.msg
// DO NOT EDIT!


#ifndef IMAGE_TO_GRID_MESSAGE_GRIDZUMY_H
#define IMAGE_TO_GRID_MESSAGE_GRIDZUMY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <image_to_grid/pixelxy.h>
#include <image_to_grid/filteredImage.h>

namespace image_to_grid
{
template <class ContainerAllocator>
struct gridZumy_
{
  typedef gridZumy_<ContainerAllocator> Type;

  gridZumy_()
    : zumy()
    , image()  {
    }
  gridZumy_(const ContainerAllocator& _alloc)
    : zumy(_alloc)
    , image(_alloc)  {
    }



   typedef  ::image_to_grid::pixelxy_<ContainerAllocator>  _zumy_type;
  _zumy_type zumy;

   typedef  ::image_to_grid::filteredImage_<ContainerAllocator>  _image_type;
  _image_type image;




  typedef boost::shared_ptr< ::image_to_grid::gridZumy_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::image_to_grid::gridZumy_<ContainerAllocator> const> ConstPtr;

}; // struct gridZumy_

typedef ::image_to_grid::gridZumy_<std::allocator<void> > gridZumy;

typedef boost::shared_ptr< ::image_to_grid::gridZumy > gridZumyPtr;
typedef boost::shared_ptr< ::image_to_grid::gridZumy const> gridZumyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::image_to_grid::gridZumy_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::image_to_grid::gridZumy_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace image_to_grid

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'image_to_grid': ['/home/cc/ee106a/fa15/class/ee106a-as/ros_ws/final_proj/src/image_to_grid/msg', '/home/cc/ee106a/fa15/class/ee106a-as/ros_ws/final_proj/src/image_to_grid/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::image_to_grid::gridZumy_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::image_to_grid::gridZumy_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_to_grid::gridZumy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_to_grid::gridZumy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_to_grid::gridZumy_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_to_grid::gridZumy_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::image_to_grid::gridZumy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c69250648b8877b3f704f49ae46fa300";
  }

  static const char* value(const ::image_to_grid::gridZumy_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc69250648b8877b3ULL;
  static const uint64_t static_value2 = 0xf704f49ae46fa300ULL;
};

template<class ContainerAllocator>
struct DataType< ::image_to_grid::gridZumy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "image_to_grid/gridZumy";
  }

  static const char* value(const ::image_to_grid::gridZumy_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::image_to_grid::gridZumy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pixelxy zumy\n\
filteredImage image\n\
\n\
================================================================================\n\
MSG: image_to_grid/pixelxy\n\
int16 x\n\
int16 y\n\
================================================================================\n\
MSG: image_to_grid/filteredImage\n\
bool[] image #true is 1, false is 0, convert with im_to_ndarray\n\
int32 length\n\
int32 width\n\
float32 comp_factor\n\
";
  }

  static const char* value(const ::image_to_grid::gridZumy_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::image_to_grid::gridZumy_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.zumy);
      stream.next(m.image);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct gridZumy_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::image_to_grid::gridZumy_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::image_to_grid::gridZumy_<ContainerAllocator>& v)
  {
    s << indent << "zumy: ";
    s << std::endl;
    Printer< ::image_to_grid::pixelxy_<ContainerAllocator> >::stream(s, indent + "  ", v.zumy);
    s << indent << "image: ";
    s << std::endl;
    Printer< ::image_to_grid::filteredImage_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMAGE_TO_GRID_MESSAGE_GRIDZUMY_H
