// Generated by gencpp from file image_to_grid/pixelxy.msg
// DO NOT EDIT!


#ifndef IMAGE_TO_GRID_MESSAGE_PIXELXY_H
#define IMAGE_TO_GRID_MESSAGE_PIXELXY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace image_to_grid
{
template <class ContainerAllocator>
struct pixelxy_
{
  typedef pixelxy_<ContainerAllocator> Type;

  pixelxy_()
    : x(0)
    , y(0)  {
    }
  pixelxy_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
    }



   typedef int16_t _x_type;
  _x_type x;

   typedef int16_t _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::image_to_grid::pixelxy_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::image_to_grid::pixelxy_<ContainerAllocator> const> ConstPtr;

}; // struct pixelxy_

typedef ::image_to_grid::pixelxy_<std::allocator<void> > pixelxy;

typedef boost::shared_ptr< ::image_to_grid::pixelxy > pixelxyPtr;
typedef boost::shared_ptr< ::image_to_grid::pixelxy const> pixelxyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::image_to_grid::pixelxy_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::image_to_grid::pixelxy_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace image_to_grid

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'image_to_grid': ['/home/cc/ee106a/fa15/class/ee106a-as/ros_ws/final_proj/src/image_to_grid/msg', '/home/cc/ee106a/fa15/class/ee106a-as/ros_ws/final_proj/src/image_to_grid/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::image_to_grid::pixelxy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::image_to_grid::pixelxy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_to_grid::pixelxy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_to_grid::pixelxy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_to_grid::pixelxy_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_to_grid::pixelxy_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::image_to_grid::pixelxy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d78a6b8c9650c754bf0432d3d1707c3";
  }

  static const char* value(const ::image_to_grid::pixelxy_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d78a6b8c9650c75ULL;
  static const uint64_t static_value2 = 0x4bf0432d3d1707c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::image_to_grid::pixelxy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "image_to_grid/pixelxy";
  }

  static const char* value(const ::image_to_grid::pixelxy_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::image_to_grid::pixelxy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 x\n\
int16 y\n\
";
  }

  static const char* value(const ::image_to_grid::pixelxy_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::image_to_grid::pixelxy_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct pixelxy_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::image_to_grid::pixelxy_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::image_to_grid::pixelxy_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMAGE_TO_GRID_MESSAGE_PIXELXY_H
