// Generated by gencpp from file image_to_grid/toTarget.msg
// DO NOT EDIT!


#ifndef IMAGE_TO_GRID_MESSAGE_TOTARGET_H
#define IMAGE_TO_GRID_MESSAGE_TOTARGET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Transform.h>
#include <geometry_msgs/Transform.h>

namespace image_to_grid
{
template <class ContainerAllocator>
struct toTarget_
{
  typedef toTarget_<ContainerAllocator> Type;

  toTarget_()
    : zumy()
    , target()  {
    }
  toTarget_(const ContainerAllocator& _alloc)
    : zumy(_alloc)
    , target(_alloc)  {
    }



   typedef  ::geometry_msgs::Transform_<ContainerAllocator>  _zumy_type;
  _zumy_type zumy;

   typedef  ::geometry_msgs::Transform_<ContainerAllocator>  _target_type;
  _target_type target;




  typedef boost::shared_ptr< ::image_to_grid::toTarget_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::image_to_grid::toTarget_<ContainerAllocator> const> ConstPtr;

}; // struct toTarget_

typedef ::image_to_grid::toTarget_<std::allocator<void> > toTarget;

typedef boost::shared_ptr< ::image_to_grid::toTarget > toTargetPtr;
typedef boost::shared_ptr< ::image_to_grid::toTarget const> toTargetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::image_to_grid::toTarget_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::image_to_grid::toTarget_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace image_to_grid

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'image_to_grid': ['/home/cc/ee106a/fa15/class/ee106a-as/ros_ws/final_proj/src/image_to_grid/msg', '/home/cc/ee106a/fa15/class/ee106a-as/ros_ws/final_proj/src/image_to_grid/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::image_to_grid::toTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::image_to_grid::toTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_to_grid::toTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::image_to_grid::toTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_to_grid::toTarget_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::image_to_grid::toTarget_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::image_to_grid::toTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54f6cde095f0ada672d5efcf4f2ed68b";
  }

  static const char* value(const ::image_to_grid::toTarget_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54f6cde095f0ada6ULL;
  static const uint64_t static_value2 = 0x72d5efcf4f2ed68bULL;
};

template<class ContainerAllocator>
struct DataType< ::image_to_grid::toTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "image_to_grid/toTarget";
  }

  static const char* value(const ::image_to_grid::toTarget_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::image_to_grid::toTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Transform zumy\n\
geometry_msgs/Transform target\n\
================================================================================\n\
MSG: geometry_msgs/Transform\n\
# This represents the transform between two coordinate frames in free space.\n\
\n\
Vector3 translation\n\
Quaternion rotation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::image_to_grid::toTarget_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::image_to_grid::toTarget_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.zumy);
      stream.next(m.target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct toTarget_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::image_to_grid::toTarget_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::image_to_grid::toTarget_<ContainerAllocator>& v)
  {
    s << indent << "zumy: ";
    s << std::endl;
    Printer< ::geometry_msgs::Transform_<ContainerAllocator> >::stream(s, indent + "  ", v.zumy);
    s << indent << "target: ";
    s << std::endl;
    Printer< ::geometry_msgs::Transform_<ContainerAllocator> >::stream(s, indent + "  ", v.target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMAGE_TO_GRID_MESSAGE_TOTARGET_H
